[workspace]
authors = ["Alex Trotta <ahajha@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "conda_bazel_build"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main = "bazel run main"
build = "bazel build ..."
format = "mojo format ."

[dependencies]
bazel = "==9.0.0"
openjdk = "<22" # Silence a warning coming from bazel
mojo = ">=1.0.0b1,<2"
clang = ">=22.1.5,<23"
sysroot_linux-64 = ">=2.28,<3"
lld = ">=22.1.5,<23" # this is also provided by mojo-compiler
gcc_impl_linux-64 = ">=15.2.0,<16"
